version: '3.9'
services:
    postgres:
        env_file:
            - .env
        image: postgres:16.2
        container_name: ${DATABASE_CONTAINER_NAME}
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASS}
        volumes:
            - ${DATABASE_VOLUME_DATA}
        ports:
            - ${DATABASE_PORT}:5432
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
